# libraries
from dataclasses import dataclass

import torch
from botorch.utils.transforms import normalize
from botorch.models.model import Model
from botorch.posteriors.gpytorch import GPyTorchPosterior

# project
from ..core.optimizerContext import OptimizationContext
from ..utils.getter import get_classes
from ..model_construction import StrategyStructure


@dataclass
class RunMetadata:
    '''
    Metadata of a run saved by the ModelSaver.
    '''
    saving_date: str
    saving_time: str

    n_inputs: int
    n_objs: int
    n_observations: int

    n_init: int
    n_repeats: int

    optimization_step: int
    init_and_opt_step: int

    description: str


@dataclass
class Objective:
    '''Helper providing the objective name and max/min boolean.'''
    name: str
    minimize: bool


class PostAnalysis:
    '''
    Helper class for loading and analyzing optimization runs saved 
    with the ModelSaver. 
    
    This class provides convenient access to the stored metadata, 
    observations, optimization contexts, and model reconstruction 
    utilities. It also allows rebuilding the optimization model at 
    different stages of the optimization process and evaluating its 
    posterior.
    '''

    def __init__(self, path: str):
        '''
        Initialize a PostAnalysis object by loading a saved optimization run. 
        
        The provided file is loaded immediately, and the corresponding 
        metadata, problem definition, observations, and summary 
        information are extracted and made available through the class 
        attributes and helper methods.
        
            Args:
                path: (str)
                    Path to a '.pt' file generated by 'ModelSaver'.
        '''

        self.load(path)     # load the data saved by ModelSaver


    def load(self, path: str) -> None:
        '''
        Load the data store in a '.pt' file made by the ModelSaver.

            Args:
                path: (str)
                    Path to the file to be loaded.
        '''
        self.data = torch.load(path, weights_only=False)

        self.metadata = self.data["metadata"]
        self.problem = self.data["problem"]
        self.observations = self.data["observations"]

        self._extract_metadata()


    def _extract_metadata(self) -> None:
        '''
        Extract the metadata from the dictionary and
        store it in the info attribute.
        '''
        meta = self.metadata
        
        description = ""
        if "description" in meta.keys():            # if the description was implemented
            description = meta["description"]       # store it

        self.info = RunMetadata(
            saving_date=meta["saving_date"],
            saving_time=meta["saving_time"],
            n_inputs=meta["n_inputs"],
            n_objs=self.observations["Y_physical"].shape[-1],
            n_observations=meta["n_observations"],
            n_init=meta["n_init"],
            n_repeats=meta["criterium"]["n_repeats"],
            optimization_step=meta["optimization_step"],
            init_and_opt_step=meta["init_and_opt_step"],
            description=description
        )
        self.summary()


    def summary(self) -> None:
        '''Display the summary of the data loaded.'''
        print(
            f"""
            Date: {self.info.saving_date} {self.info.saving_time}
            Observations: {self.info.n_observations}
            Inputs: {self.info.n_inputs}
            Objectives: {self.info.n_objs}
            Initial observations: {self.info.n_init}
            Repeats: {self.info.n_repeats}
            Steps: {self.info.init_and_opt_step}
            Description: {self.info.description}
            """
        )


    @property
    def X_physical(self):
        return self.observations["X_physical"]

    @property
    def Y_physical(self):
        return self.observations["Y_physical"]

    @property
    def X_normalized(self):
        return self.observations["X_normalized"]

    @property
    def Y_opt_space(self):
        return self.observations["Y_opt_space"]
    
    @property
    def X_opt(self):
        return self.X_physical[self.info.n_init:]

    @property
    def Y_opt(self):
        return self.Y_physical[self.info.n_init:]

    @property
    def shot_numbers(self):
        return self.observations["shot_numbers"]


    def get_n_observations(self, step: int) -> int:
        '''
        Get the number of obervations made at the given 
        initialization + optimization 'step'.

            Args:
                step: (int)
                    The step at which we aim to get the 
                    number of observations.
            
            Returns:
                The number of observations made.
        '''
        if not isinstance(step, int):
            raise TypeError(
                f"'step' argument must be an interger, note {type(step)}."
            )

        if step < 1:
            raise ValueError("step must be >= 1")

        if step > self.info.init_and_opt_step:
            raise ValueError(
                f"step={step} exceeds max step "
                f"{self.info.init_and_opt_step}"
            )

        if step == 1:                   # first step is the initialization
            return self.info.n_init
        
        return self.info.n_init + (step - 1) * self.info.n_repeats   # return the number of observations at the given step


    def get_context_at_step(self, step: int) -> OptimizationContext:
        '''
        Build an optimization context with the observations
        made until the step 'step'. If step is None, we consider
        the last step.

            Args:
                step: (int)
                    The step at which we aim the construct
                    the optimization context.
            
            Returns:
                The optimization context build with the 'step' observations.
        '''
        # get the number of observations made at the given step
        n_obs = self.get_n_observations(step=step)

        # make the objective helper
        objs = {}
        for name, obj_dict in self.problem["objectives"].items():
            objs[name] = Objective(name, minimize=obj_dict["minimize"])

        # build the context
        ctx = OptimizationContext(
            bounds=self.problem["bounds"],
            objectives=objs,
            inputs=self.problem["inputs"],
        )

        # filter the observations until the step required
        X = self.X_physical[:n_obs]
        Y = self.Y_physical[:n_obs]
        shots = self.shot_numbers[:n_obs]

        # add each observation to the context
        for x, y, shot in zip(X, Y, shots):
            ctx.add_observation(
                x=x,
                y=y,
                shot_number=shot,
            )

        # set the context initialization number
        ctx.n_init = self.info.n_init
        
        # set the context step
        ctx.set_step(step=step)
        
        return ctx


    def get_initial_context(self) -> OptimizationContext:
        '''Helper to get the context after initialization.'''
        return self.get_context_at_step(step=1)


    def get_final_context(self) -> OptimizationContext:
        '''Helper to get the context after final step.'''
        step = self.info.init_and_opt_step
        return self.get_context_at_step(step=step)


    def reconstruct_model(self, ctx: OptimizationContext):
        '''
        Reconstruct and fit the model saved in the loaded file
        from a given context. The model is retrained, which
        might change the model hyperparameters compare to the
        first training.
        
            Args:
                ctx: (OptimizationContext)
                    Context at which the model must be reconstruct.
            
            Return:
                A fitted model retrained.
        '''
        strat, params = self.identify_strategy()
        model = strat.build_model(context=ctx, **params)
        model = strat.fit_model(model=model)
        print("Model reconstructed.")
        return model


    def rebuild_model(self, ctx: OptimizationContext) -> Model:
        '''
        Rebuild the model saved in the loaded file from a
        given context. If possible, the model is fitted
        using the state dictionary of the first training,
        to keep the same hyperparameters. Otherwise, return
        a model reconstructed (i.e. retrained).

            Args:
                ctx: (OptimizationContext)
                    Context at which the model must be reconstruct.
            
            Returns:
                A fitted model rebuilt or retrained
        '''
        strat, params = self.identify_strategy()
        model = strat.build_model(context=ctx, **params)
        print("Model built.")
        model = self._load_model_state(
            model=model,
            step=ctx.step
        )
        return model


    def get_posterior(self,
                    x_physical: torch.Tensor,
                    step: int | None = None) -> tuple[dict[str, GPyTorchPosterior], dict[str, torch.Tensor], dict[str, torch.Tensor]]:
        '''
        Sample the posterior at the given step.

            Args:
                x_physical: (torch.Tensor)
                    The position at which sample the posterior.
                
                step: (int | None)
                    The step at which sample the posterior.
            
            Returns:
                Three dictionaries, each having the objectives as key and
                the posterior, the mean and the std of the model as value.
        '''
        if step is None:                              # if step is None
            step = self.info.init_and_opt_step        # use the last step
        
        strat, params = self.identify_strategy()      # get the strategy

        ctx = self.get_context_at_step(step=step)     # make the context at the given step
        
        model = self.rebuild_model(ctx=ctx)

        # the input to sample should be in normalized space
        X_norm = normalize(x_physical, ctx.bounds)
        names = [obj.name for obj in ctx.objectives.values()]   # the objectives names

        post, mean, std = strat.posterior(
            names=names,
            model=model,
            X_norm=X_norm
        )
        return post, mean, std


    def _load_model_state(self, model: Model, step: int) -> Model:
        '''
        Fit a model using the state dictionary, to keep the
        same wighets as during first training. If not available,
        the model is retrained.

            Args:
                model: (Model)
                    The model we want to load or retrain.
                
                step: (int)
                    The step at which we are looking for hyperparameters.
        
            Returns:
                A fitted model, either using the former weights or
                strategy fit method.
        '''
        # get the model dictionary from the loaded file
        model_data = self.data.get("model", {})
        
        last_step = self.info.init_and_opt_step
        is_history = "model_state_history" in model_data
        is_model_state = "model_state_dict" in model_data
        
        # using history
        if step != last_step and is_history:              # if it's not the last step and there is the state dict history
            history = model_data["model_state_history"]   # get the history dictionary

            if step in history:             # if the step is in the history
                model.load_state_dict(      # load the correspondign state dict
                    history[step], 
                )
                model.eval()
                print("Model state history restaured.")
                return model

        # using model_state_dict
        elif step==last_step and is_model_state:    # if it's the last step
            model.load_state_dict(                  # load the corresponding state dict
                model_data["model_state_dict"], 
            )
            model.eval()
            print("Model state restaured.")
            return model

        else:
            strat, params = self.identify_strategy()   # get the strategy
            model = strat.fit_model(model)             # fit the model
            print(
                "Impossible to use the state dictionary.\n"
                "The model had to be reconstructed."
            )

        return model


    def identify_strategy(self) -> tuple[StrategyStructure, dict]:
        '''
        Helper that return the strategy and the parameters 
        used in the loaded file.

            Returns:
                The instanciated strategy and the parameter dictionary
        '''
        # get the strategies in model_construction
        strategies = get_classes("strategies")

        # get the strategy and the parameters from the loaded data
        strat = self.data["problem"]["strategy"]
        strat_cls = self.data["problem"]["strategy"]["class"]

        strategy = None     # identified strategy

        for name, cls in strategies.items():   # loop among the strategies

            # match by class name or full path
            if strat_cls.endswith(name) or strat_cls == name:
                strategy = cls()        # we identified the right one and instanciate it
                break                   # we stop the loop

        if strategy is None:    # if strategy is still None we did not find it
            raise ValueError(
                f"Unknown strategy: {strat}. "
                f"Available: {list(strategies.keys())}"
            )
        
        return strategy, strat["params"]